import Link from "next/link";
import { ArrowUpRight, CheckCircle2 } from "lucide-react";
import { Container } from "@/components/ui/container";
import { Reveal } from "@/components/shared/Reveal";

const serviceLinks = [
  ["Technical SEO", "/services/technical-seo", "Improve crawlability, indexation, site speed, structured data, and the technical foundation search engines rely on."],
  ["On-Page SEO", "/services/seo#on-page-seo", "Align titles, headings, copy, internal links, entities, and conversion paths with search intent."],
  ["Local SEO", "/services/local-seo", "Improve visibility for location-based searches, map discovery, calls, enquiries, and local trust."],
  ["SEO Content Writing", "/services/seo-content-writing", "Create service pages, blogs, and topical authority content that answers real customer questions."],
  ["Off-Page SEO", "/services/off-page-seo", "Build relevant authority through digital PR, citations, partnerships, mentions, and defensible link acquisition."],
  ["Content Marketing", "/services/content-marketing", "Turn research and content clusters into a consistent system for discovery, trust, and qualified demand."],
] as const;

const process = [
  ["SEO Audit", "Review technical health, indexation, content quality, internal links, competitors, analytics, and conversion paths."],
  ["Keyword Research", "Map search intent, customer language, commercial opportunities, entities, and realistic ranking targets."],
  ["Competitor Analysis", "Study the pages, topics, offers, links, SERP features, and gaps that shape the competitive landscape."],
  ["Content Strategy", "Build pillar, cluster, service, local, and supporting content plans connected by deliberate internal links."],
  ["On-Page Optimization", "Improve titles, headings, copy, metadata, schema opportunities, user experience, and calls to action."],
  ["Technical Optimization", "Prioritize crawlability, indexation, performance, redirects, canonicals, sitemaps, and structured data."],
  ["Authority Building", "Earn relevant mentions and links while strengthening the brand signals that support organic visibility."],
  ["Performance Monitoring", "Track rankings, impressions, clicks, qualified conversions, page performance, and the next optimization cycle."],
] as const;

export function SeoServicesContent() {
  return <>
    <section className="border-t border-border py-20"><Container className="max-w-4xl"><Reveal><p className="text-sm font-semibold uppercase tracking-wide text-primary">Search Engine Optimization</p><h2 className="mt-3 text-[length:var(--text-h2)] font-display font-bold tracking-tight">What Are SEO Services?</h2><div className="mt-5 space-y-4 text-[length:var(--text-body-lg)] leading-8 text-muted-foreground"><p>SEO services improve how a website is discovered, understood, trusted, and selected in organic search. The work connects technical SEO, keyword research, search intent, useful content, internal linking, local visibility, schema markup, and authority building with the business outcome that matters—qualified enquiries, sales, bookings, or growth in the right audience.</p><p>A strong SEO programme is not a promise to rank for one keyword. It is a structured system that helps the right pages appear for the right questions, gives visitors a clear next step, and creates useful evidence for the next decision.</p></div></Reveal></Container></section>
    <section id="on-page-seo" className="bg-surface py-20"><Container><Reveal className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-wide text-primary">SEO service areas</p><h2 className="mt-3 text-[length:var(--text-h2)] font-display font-bold tracking-tight">Our SEO Services</h2><p className="mt-4 text-muted-foreground">Choose the specialist work your website needs, or combine the areas into one topical authority and organic growth programme.</p></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{serviceLinks.map(([title, href, text], index) => <Reveal key={title} delay={index * 0.04}><Link href={href} className="group block h-full rounded-xl border border-border bg-card p-6 shadow-soft transition-all hover:-translate-y-1 hover:shadow-elevated"><div className="flex items-start justify-between gap-3"><h3 className="font-display text-xl font-bold tracking-tight">{title}</h3><ArrowUpRight className="size-5 shrink-0 text-primary" /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></Link></Reveal>)}</div></Container></section>
    <section className="py-20"><Container className="max-w-5xl"><Reveal className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-wide text-primary">A repeatable operating model</p><h2 className="mt-3 text-[length:var(--text-h2)] font-display font-bold tracking-tight">Our SEO Process</h2><p className="mt-4 text-muted-foreground">The sequence adapts to the site, market, and team, but every recommendation is connected to evidence and a measurable next step.</p></Reveal><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{process.map(([title, text], index) => <Reveal key={title} delay={index * 0.035} className="rounded-xl border border-border bg-card p-5"><div className="flex items-center gap-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground">{index + 1}</span><h3 className="font-semibold">{title}</h3></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{text}</p></Reveal>)}</div></Container></section>
    <section className="border-y border-border bg-surface py-20"><Container className="grid gap-12 lg:grid-cols-2"><Reveal><p className="text-sm font-semibold uppercase tracking-wide text-primary">Why this approach</p><h2 className="mt-3 text-[length:var(--text-h2)] font-display font-bold tracking-tight">Why Choose Mahedi Hasan for SEO?</h2><div className="mt-5 space-y-4 text-muted-foreground"><p>The work is grounded in clear architecture, useful content, honest measurement, and practical implementation. Recommendations are prioritised by impact, evidence, and the capacity of the business to act.</p><p>That means no fake rankings, fake reviews, guaranteed traffic claims, or generic checklist delivered without context. The goal is a search system that becomes more useful and more measurable over time.</p></div></Reveal><Reveal delay={0.1}><h2 className="text-[length:var(--text-h2)] font-display font-bold tracking-tight">Who Can Benefit From Our SEO Services?</h2><ul className="mt-5 space-y-4 text-muted-foreground">{["Local businesses that need more qualified calls, enquiries, bookings, or map visibility.", "Service businesses competing for high-intent searches and complex customer decisions.", "E-commerce and product brands that need better category, product, and content discovery.", "B2B and international businesses building topical authority across a competitive market.", "Teams that need an SEO roadmap, specialist execution, or a clear second opinion on existing work."].map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 size-5 shrink-0 text-primary" /><span>{item}</span></li>)}</ul></Reveal></Container></section>
    <section className="py-20"><Container className="max-w-4xl"><Reveal className="text-center"><p className="text-sm font-semibold uppercase tracking-wide text-primary">Evidence over promises</p><h2 className="mt-3 text-[length:var(--text-h2)] font-display font-bold tracking-tight">SEO Results and Case Studies</h2><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">Review the strategy and evidence behind real organic search engagements, including local architecture, technical SEO, content systems, and measurable visibility growth.</p><Link href="/case-studies" className="mt-6 inline-flex items-center gap-2 font-semibold text-primary hover:underline">Explore SEO case studies <ArrowUpRight className="size-4" /></Link></Reveal></Container></section>
    <section className="border-t border-border bg-surface py-16"><Container className="max-w-4xl"><Reveal><h2 className="text-[length:var(--text-h2)] font-display font-bold tracking-tight">SEO Standards and Measurement</h2><p className="mt-4 text-muted-foreground">Recommendations are checked against current search documentation and first-party measurement wherever possible. Useful references include <a className="font-medium text-primary hover:underline" href="https://developers.google.com/search/docs" target="_blank" rel="noreferrer">Google Search Central</a>, <a className="font-medium text-primary hover:underline" href="https://search.google.com/search-console/about" target="_blank" rel="noreferrer">Google Search Console</a>, and <a className="font-medium text-primary hover:underline" href="https://pagespeed.web.dev/" target="_blank" rel="noreferrer">PageSpeed Insights</a>.</p></Reveal></Container></section>
  </>;
}
